### ISSUE TITLE
ssh connect hangs if the device cannot be found

### ISSUE THREAD

**Issue by andrewvh4** [LangenGroup/RedPitayaSTCL#2]
ssh connect hangs if the device cannot be found:

https://github.com/LangenGroup/RedPitayaSTCL/blob/f5bec44b9492a81275b989f265fa5b672dc28a1e/communication.py#L192C1-L192C1

Steps to reproduce:
1. Disconnect the host computer from the network containing the RPTs
2. Add the following debug print statements around the aforementioned line
```python
print("Pre Connect")
ssh.connect(hostname, port = 22, username='root', password = 'root')
print("Post Connect")
```

I received the following terminal output
```
/home/andrew/miniconda3/envs/STCL/lib/python3.10/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Pre Connect
```
The program then freezes.

**Comment by LangenGroup** [comment]
Added a timeout to fix this.
